fortran:
  experiment_name: decaying_turbulence
data:
  creation_method: average
  vortex_mean: 0.0
  vortex_std: 16.0
  scale: 9
  image_width: 128
  image_height: 128
model:
  name: Eq-RRDN
  in_channels: 1
  out_channels: 1
  kernel_size: 3
  num_layers: 3
  num_blocks: 3
  degree_rotation: 4
  feature_type: "regular_repr,16"
  growth_type: "regular_repr,16"
  post_feature_type: "regular_repr,16"
train:
  batch_size: 32
  early_stopping_patience: 30
  num_epochs: 5000
  lr: 3.3e-04
  seed: 42
