fortran:
  experiment_name: barotropic_instability
data:
  creation_method: average
  vortex_mean: 0.0
  vortex_std: 0.20
  scale: 9
model:
  name: DSC-MS
  in_channels: 1
  out_channels: 1
  factor_filter_num: 1
train:
  batch_size: 100
  early_stopping_patience: 30
  num_epochs: 5000
  lr: 1.0e-03
  seed: 42
