fortran:
  experiment_name: decaying_turbulence
data:
  creation_method: subsample
  velocity_mean: 0.0
  velocity_std: 14.0
  scale: 9
  image_width: 128
  image_height: 128
model:
  name: RRDN
  in_channels: 2
  out_channels: 2
  kernel_size: 3
  num_layers: 3
  num_blocks: 3
  num_features: 64
  growth_rates: 64
  num_post_features: 64
train:
  batch_size: 32
  early_stopping_patience: 30
  num_epochs: 5000
  lr: 6.6e-04
  seed: 42
