fortran:
  experiment_name: barotropic_instability_spectral_nudging
data:
  creation_method: spectral_nudging
  vortex_mean: 0.0
  vortex_std: 0.32
  LR_name: T10
  HR_name: T42
model:
  name: DSC-MS
  in_channels: 1
  out_channels: 1
  factor_filter_num: 1
train:
  batch_size: 100
  early_stopping_patience: 30
  num_epochs: 5000
  lr: 1.0e-03
  seed: 42
