fortran:
  experiment_name: barotropic_instability_spectral_nudging
data:
  creation_method: spectral_nudging
  u_mean: 0.0
  u_std: 0.6
  v_mean: 0.0
  v_std: 0.1
  LR_name: T10
  HR_name: T42
model:
  name: RRDN
  in_channels: 2
  out_channels: 2
  kernel_size: 3
  num_layers: 3
  num_blocks: 3
  num_features: 64
  growth_rates: 64
  num_post_features: 64
train:
  batch_size: 32
  early_stopping_patience: 30
  num_epochs: 5000
  lr: 1.1e-04
  seed: 42
