fortran:
  experiment_name: barotropic_instability_spectral_nudging
data:
  creation_method: average
  vortex_mean: 0.0
  vortex_std: 0.32
  LR_name: T10
  HR_name: T42
model:
  name: Eq-RRDN
  in_channels: 1
  out_channels: 1
  kernel_size: 3
  num_layers: 3
  num_blocks: 3
  degree_rotation: 2
  feature_type: "regular_repr,32"
  growth_type: "regular_repr,32"
  post_feature_type: "regular_repr,32"
train:
  batch_size: 32
  early_stopping_patience: 30
  num_epochs: 5000
  lr: 3.3e-04
  seed: 42
