fortran:
  experiment_name: barotropic_instability
data:
  creation_method: subsample
  u_mean: 0.0
  u_std: 0.42
  v_mean: 0.0
  v_std: 0.42
  scale: 9
model:
  name: Eq-RRDN
  in_channels: 2
  out_channels: 2
  kernel_size: 3
  num_layers: 3
  num_blocks: 3
  degree_rotation: 2
  feature_type: "regular_repr,32"
  growth_type: "regular_repr,32"
  post_feature_type: "regular_repr,32"
train:
  batch_size: 32
  early_stopping_patience: 30
  num_epochs: 5000
  lr: 3.3e-04
  seed: 42
